version: "3"
services:
  gptstudio:
    container_name: "gptstudio"
    image: teamsgpt.azurecr.io/gptstudio:latest
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    env_file:
      - .env
    volumes:
      - gptstudio-volume:/data
    ports:
      - "8501:8501"
    command: ["streamlit","run", "gptstudio.py"]
    restart: always
    networks:
      gptstudio_network:


networks:
  gptstudio_network:

volumes:
  gptstudio-volume:
