name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to Azure Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to TTI Packages
        uses: docker/login-action@v2
        with:
          registry: teamsgpt.azurecr.io
          username: ${{ secrets.TTI_DOCKER_USERNAME }}
          password: ${{ secrets.TTI_DOCKER_PASSWORD }}

      - name: Build image and push to Azure Container Registry
        uses: docker/build-push-action@v3
        with:
          context: ./
          tags: |
            teamsgpt.azurecr.io/gptstudio:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
          push: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' }}
